### ISSUE TITLE
Discussion: Managing implementation details for message data types

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#22]
As we progress with implementing import/exporting protobuf files we've come across some design questions regarding how we manage the complexity of implementation details with the abstract/generic definition of the AaC DSL. For instance, protobuf3 has an extensive list of supported data types [see the table here](https://developers.google.com/protocol-buffers/docs/proto3#scalar), but the AaC DSL currently only defines the following primitives (string, int, number, bool, date, file). As we map messages defined in AaC to these more complex protobuf implementations, we will be forced to either push extra complexity into the AaC definition or limit the protobuf3 implementation. 

In the current AaC language design what would the strategy be for allowing a system engineer to define a message without the complexity of understanding signed vs unsigned integers while not preventing the protobuf implementation from using signed vs unsigned integers?

This discussion is directed at generating data messages, but this same problem of moving from abstract -> concrete details will impact more than just the data message generation as we'll have the same problem when we're looking to generate other aspects of the architecture that are presented abstractly to the systems engineer who is modelling the system (e.g. infrastructure and service implementations).

**Comment by Coffee2Bits** [comment]
I agree with Cameron that a path forward would be to allow users to incrementally transition from abstract definitions to more concrete definitions. The type/sub-type strategy could be effective, that's the initial idea I had for my jellyfish v3 DSL, but it certainly adds a lot of complexity to the DSL and project. 

We can alternatively just provide an extensive set of primitive data definitions to cover the general primitive data types that you'd find in programming languages (e.g. double, float, uint32, uint64, int32, int64, and bytes) and allow the team employing AaC to introduce the complexity themselves. For example, the systems engineer would create a message and use the generic type 'number' then another team member, such as a developer, would change the generic 'number' to a more concrete type 'uint64'. Of course, this method wouldn't hide the implementation details from the systems engineer who will now have to interact with 'uint64' every time they interact with our example message.

**Comment by jondavid-black** [comment]
The strategy we used for Jellyfish 2.0 was to "model the deployment" by extending the model with a set of attributes required to make the transition from abstract to concrete.  Perhaps we could consider something similar here.

Example:  https://github.com/NorthropGrumman/jellyfish/blob/master/jellyfish-examples/system-descriptor-projects/threat-eval-system-descriptor/src/main/sd/com/ngc/seaside/threateval/deployment/DemoThreatEvalDeployment.sd

I think this is an area where we should also consider a transition from one stakeholder type to another in the the workflow.  Someone interested in deciding between signed vs unsigned int is probably not someone dealing with top level system decomposition and use cases.  We certainly need to preserve the abstract.  Ideally we do that without driving too much complexity into the model specification itself.

Here's an initial thought...based off the JF experience.  Let's create a 'refine' root type that collects 'concrete implementation data' to be used by a tool performing the generation.  For a document, this may be something specifying an html template and css.  For Protobuf, this may be something that maps a AaC data type to a Protobuf data type.  Take a look at the extension root type and see if that concept may apply here. If we need, we could make this more complex by allowing nesting.

BTW...not a huge fan of the name 'refine', but don't have a better idea right now.

**Comment by jondavid-black** [comment]
Gents...please keep your eye on the project page in this repo.  I'm trying to keep track of things there in a kanban board.

This discussion pushed me to look at #21 and do some thinking.  I've realized that even though we're just getting started we already have some tech debt...mostly driven by my lack of python experience and the fact this started as a gradle driven java project before switching to python.

I think it is in our best interest to overcome that tech debt before we continue with this capability.  I've created a couple stories and put them at the top of the kanban to address that.  Given we're in the early stages, let's be sure to quickly identify and resolve tech debt...otherwise we'll struggle to meet our objectives in the time we've got.

**Comment by Coffee2Bits** [comment]
> The strategy we used for Jellyfish 2.0 was to "model the deployment" by extending the model with a set of attributes required to make the transition from abstract to concrete. Perhaps we could consider something similar here.
> 
> Example: https://github.com/NorthropGrumman/jellyfish/blob/master/jellyfish-examples/system-descriptor-projects/threat-eval-system-descriptor/src/main/sd/com/ngc/seaside/threateval/deployment/DemoThreatEvalDeployment.sd
> 
> I think this is an area where we should also consider a transition from one stakeholder type to another in the the workflow. Someone interested in deciding between signed vs unsigned int is probably not someone dealing with top level system decomposition and use cases. We certainly need to preserve the abstract. Ideally we do that without driving too much complexity into the model specification itself.
> 
> Here's an initial thought...based off the JF experience. Let's create a 'refine' root type that collects 'concrete implementation data' to be used by a tool performing the generation. For a document, this may be something specifying an html template and css. For Protobuf, this may be something that maps a AaC data type to a Protobuf data type. Take a look at the extension root type and see if that concept may apply here. If we need, we could make this more complex by allowing nesting.

I like the idea of the refine/deployment model that you linked from the JF repository--it reminds me of passing args to a terraform module to add extra context and implementation detail. That being said, if we used the `refine` properties to further define data types then there is a possibility that the refined data types will conflict with the abstract data types. We could just 'allow' this overriding behavior and treat the abstract message definition as the general structure of the data model while the refined properties as the source of truth for the data types. If we implemented this two-tiered definition for data models and  if we don't implement any validation, then we would encounter some confusing/conflicting situations, like an abstract type `string` being overridden/implemented as a `uint32` type:

Message.yaml
```
data: 
  name: Message
  fields:
  - name: body
    type: string
  - name: sender
    type: string
 ---
 refine:
   target: Message
   properties:
   - fields.body.type: string
   - fields.sender.type: uint32
```

If we want to avoid the above situation we could leverage a type/subtype system for data types so that the modeler defines an abstract type, like `number` that would confine the developer's implementation type to a `number` sub-type like `int32`, `uint32`, `int64`, `uint64`, `float`, `double`. That being said, our first implementation can ignore validation of the abstract -> implementation data type.

I agree that `refine` doesn't sound like the best keyword. I'll throw `implementation` into the ring for consideration since the content under the `implementation` node will be just that: implementation details. It would look something like:

Message.yaml
```
data: 
  name: Message
  fields:
  - name: body
    type: string
  - name: sender
    type: string
  - name: message_id
    type: number
 ---
 implementation:
   implements: Message # Target any data or model definition by name
   properties:
   - fields.body.type: string
   - fields.sender.type: string
   - fields.message_id.type: uint32
```

**Comment by cvchaparro** [comment]
I recall the model/deployment structure we had in Jellyfish 2 (and, in fact, proposed a variation of that in my [example](https://gitlab.com/cvcf/cubozoa/-/blob/master/example/alarm/impl/configuration.lisp) that I called a `configuration`). In fact [here](https://gitlab.com/cvcf/cubozoa/-/blob/master/example/alarm/impl/configuration.lisp#L14-24) I was proposing something akin to what Alex proposes above.

I mention all of this to say that I like the idea of re-using the `deployment` and `refine` functionality from Jellyfish 2 and I would be happy to switch to using `implementation` (or `configuration`) over `refine` - whichever makes the most sense.
