### ISSUE TITLE
I want an additional plugin failure code that identifies missing definitions/values for generation type plugins

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#288]
As an AaC user, I want an additional plugin failure code that identifies missing definitions for generation-type plugins, so that I immediately understand that the issue is a deficiency in my source files.

## AC:
- [ ] A new plugin status code is added which indicates missing required definitions.
- [ ] If a plugin relies on some definition or definition structures to 'drive' its generation, it must return the new missing information code if those definitions are missing.
    - (e.g. gen-plugin without models, gen-protobuf without messages, or gen-gherkin without behaviors)
- [ ] Any error messages with the status code must clearly indicate what is expected, but missing
- [ ] The gen-plantUML plugin is updated to use this new code for demostration 

### Notes:
Gen-protobuf is a good place to examine this impact. The primitives provided from the gen-protobuf plugin are not clearly communicated to end user if you are missing those primitives in your model

**Comment by lizzcondrey** [comment]
As we have split out the plugins to be standalones, the generation centric plugins do return error notices if you provide a model that does not contain the needed content. Closing this issue since this is now practice for developing the generate type plugins
