### ISSUE TITLE
I want a validator plugin that returns warnings for undefined fields

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#429]
As a user, I want a validator plugin that returns warnings for undefined fields, so that I receive warnings for using undefined fields.

~~(Stretch) Suggest a defined field name if the string difference is mininmal i.e. `strung` -> `string`~~

## AC:
- [x] A new validator is created for undefined fields
- [x] A unit test for the validator is created
- [ ] The validator is added to the pipeline core validators if necessary
- [ ] The validator documentation is updated to cover the new validator
- [x] Validation finding returns a error
- [ ] Check on field:name on the schema definition

**Comment by lizzcondrey** [comment]
Pulling out the stretch portion of the description to a separate story to keep the complexity more manageable for this task. The associated issue for the stretch is [here](https://github.com/DevOps-MBSE/AaC/issues/678)
