### ISSUE TITLE
Gen-Plugin should leverage modeled attributes to generate contribution points accordingly

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#433]
As an AaC Developer, I want Gen-Plugin to generate constraint contribution point stubs of a new plugin, so that user's options and implementations are more distinct and apparent.

##AC:
- [ ] Gen-Plugin must generate contribution points based on the plugin model
  - [ ] If there are constraints present, constraint contribution points are generated
    - [ ] Schema/Structure constraints are created as appropriate 
    - [ ] Primitive/Enum/Value constraints are created as appropriate
    - [ ] Context/Global constraints are created as appropriate
- [ ] Include a field to plugin schema to accept Context/Global constraint type contributions

## Resources for the confirm AC
https://github.com/jondavid-black/AaC/blob/b2e16e4a8d868a74556aeae3cb0538b6b0e010a7/python/src/aac/spec/spec.yaml#L574-L593
https://github.com/jondavid-black/AaC/blob/main/python/src/aac/plugins/first_party/gen_plugin/gen_plugin_impl.py#L87-L104
https://github.com/jondavid-black/AaC/blob/main/python/src/aac/plugins/first_party/gen_plugin/gen_plugin_impl.py#L87-L104
https://github.com/jondavid-black/AaC/blob/b2e16e4a8d868a74556aeae3cb0538b6b0e010a7/python/src/aac/plugins/first_party/gen_plugin/templates/first_party/__init__.py.jinja2#L29-L31
black/AaC/blob/b2e16e4a8d868a74556aeae3cb0538b6b0e010a7/python/src/aac/plugins/first_party/gen_plugin/templates/first_party/__init__.py.jinja2#L69-L71

**Comment by lizzcondrey** [comment]
Reshuffled tasking around, so this issue is no longer needed.
