### ISSUE TITLE
I want the Subcomponent Type validator overhauled to use keyword arguments for type and field

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#454]
As an AaC user, I want the Subcomponent Type validator overhauled to use keyword arguments for type and field, so that I can specify type constraints for individual fields.

## References: 
[Subcomponent Validator](https://github.com/jondavid-black/AaC/blob/3dfc11baf0ec8d7250608bd16caebdae837fc8af/python/src/aac/plugins/validators/subcomponent_type/_subcomponent_type.py)

Current validator:
https://github.com/jondavid-black/AaC/blob/3dfc11baf0ec8d7250608bd16caebdae837fc8af/python/src/aac/spec/spec.yaml#L393-L394

Expected validator:
```yaml
  validation:
    - name: Field is type
      kw_args:
        - name: components
          type: model
```

Interface to update for KW arguments.
https://github.com/jondavid-black/AaC/blob/3dfc11baf0ec8d7250608bd16caebdae837fc8af/python/src/aac/validate/_validate.py#L150

Example plugin validator signature to update: https://github.com/jondavid-black/AaC/blob/3dfc11baf0ec8d7250608bd16caebdae837fc8af/python/src/aac/plugins/validators/root_keys/_validate_root_keys.py#L12-L17

## AC:
- [ ] Definition validations are updated to provide support for keyword arguments
  - [ ] Users can use list arguments or KW arguments
- [ ] The validator documentation is updated to include using keyword arguments
- [ ] The Subcomponent Type validator is updated to use keyword arguments
  - [ ] The key is the field to validate
  - [ ] The value defines what the type must be
- [ ] The Subcomponent Type validator is renamed to "Field Type"
- [ ] All first-party definition validator validation function signatures are updated with the keyword args.

**Comment by Coffee2Bits** [comment]
I've given this some thought, and any sort of validation of the arguments, or allowing users to use arrays and dicts within the `arguments` field -- all of which requires additional functionality. Going to move this out until the dependent functionality can be identified.

**Comment by lizzcondrey** [comment]
This is now stale and has been reworked within the new 0.4.0 baseline, closing it out.
