### ISSUE TITLE
I want a criteria for good first issues.

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#493]
I want a documented criteria for what constitutes a good first issue.

## AC:
- [ ] There is a new wiki page documenting the criteria for good first issues

**Comment by lizzcondrey** [comment]
Possible criteria:
- Keep scoped to tasks that would not require knowledge of the full tool or project to complete.
  - A simple constraint.
  - A simple plugin: i.e. gen-json
- Small enough that a new team member could complete on their own with minimal assistance.
  - Should not require paired programming type efforts with a more senior team member. 
- Tasks that leverage more Python knowledge than AaC knowledge. 
- Could be a small, timeboxed, research/investigation task.
  - Should be separate from any follow on implementation task based on findings of an investigation. 
- Could be smaller piece of a larger task that does not need to be "figured out how to do", but leveraging existing components, established patterns, etc. 
  - Should mimic something already within the codebase, that if questions are asked an existing developer could direct the new member where to look for an example.

**Comment by lizzcondrey** [comment]
Here is a link to the [wiki page](https://github.com/DevOps-MBSE/AaC/wiki/Good-First-Issue-Criteria) with this write up.
