### ISSUE TITLE
JSON Schema for usecases throws an exception due to max recursion depth

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#495]
The JSON Schema for usecases throws an exception due to max recursion depth, because the definition `Branch` has `Step` which in turn has `Branch` creating a recursive cycle with no end. 

## References
The `Branch` definition
https://github.com/jondavid-black/AaC/blob/2a29543e1630edd52f82f63d1f9609f9a5621551/python/src/aac/spec/spec.yaml#L462-L477

The `Step` definition
https://github.com/jondavid-black/AaC/blob/2a29543e1630edd52f82f63d1f9609f9a5621551/python/src/aac/spec/spec.yaml#L428-L460

## AC:
- [ ] ..? The fix should probably be to either adjust the function to gracefully fail
- [ ] The JSON schema function maintains a "running count" of the field types visited, and when a recursive loop is detected "x -> y -> x", the json schema function terminates.

### Note:
This is primarily for usage with the restAPI, especially for the visual editor component

**Comment by lizzcondrey** [comment]
We modified the core definitions and understanding of use cases, have not hit this issue since migrating, so closing.
