### ISSUE TITLE
I want the Core Spec to be moved into the `aac.lang` package

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#511]
I want the Core Spec to be moved into the `aac.lang` package.

## AC:

1. The core spec is moved into the `aac.lang` package.
2. References to the core spec are updated
3. References to the core spec in the docs are updated

**Comment by lizzcondrey** [comment]
This is now stale and was reworked within the 0.4.0 baseline covered by #714 . Closing it out.
