### ISSUE TITLE
I want a test state file to be auto-generated

### ISSUE THREAD

**Issue by cvchaparro** [DevOps-MBSE/AaC#516]
As a developer, I want a test state file to be auto-generated so that I can run tests without having to remove the state file.

The desire for this came from a test failure in `tests.cli.test_execute` due to my local state file being written using version `0.1.5` and the `aac` version just being bumped to version `0.1.6` (in commit 44f2902377a4efa50c0ea291e0ed154bb95f06fd). The failure was caused when importing the state file due to the versions being different.

The goal here is that running tests will never fail due to version mismatch (unless that is the expected/desired outcome).

## AC

- [ ] A state file is created for use by the tests.
- [ ] The test state file is removed upon test completion (whether there were test failures, or not).
  - I'm not totally sure this is what we'd want (maybe we want an option to keep the state file for debugging purposes?)
- [ ] ???

**Comment by lizzcondrey** [comment]
Per working PR #714 and [this comment thread](https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1431869103), this task was determined to be eligible for closure.
