### ISSUE TITLE
Exception in Validating Spec

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#537]
https://github.com/jondavid-black/AaC/blob/2f169720383a8134094aabc5c0d7ca9c5cb6c51f/python/src/aac/plugins/first_party/specifications/referenced_ids_exist.py#L49

Getting error when validating a specification:
```
Validator 'Reference IDs exist' failed with an exception:  type of lexeme must be aac.lang.definitions.lexeme.Lexeme; got NoneType instead
```

There's nothing obvious at the moment as to what may be wrong, so it'll take a little work to document the instructions to recreate the issue for testing.

**Comment by lizzcondrey** [comment]
The way that validate works (now check) has changed since the re-baseline of #714 and specification plugin was extracted and is currently being reworked. 

@bunchw , be mindful about this as you work through re-implementing the specifications plugin as a stand alone.
