### ISSUE TITLE
Investigate dynamically including code snippets in wiki

### ISSUE THREAD

**Issue by cvchaparro** [DevOps-MBSE/AaC#592]
Generated from [this PR comment](https://github.com/jondavid-black/AaC/pull/557#discussion_r1141473706).

As an AaC documenter, I want to improve my code references within my documentation, so that dynamic cross references are used instead of pasted snippets, so that my documentation references the proper code snippets. 

##AC:
- [ ] Remove out of date code snippets
- [ ] Incorporate dynamic references to necessary code snippets
- [ ] Verify published documentation uses the new code references

**Comment by lizzcondrey** [comment]
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-sourcecode

If we swap all documentation over to Sphinx (as I am considering for addressing #118), this becomes doable if I am understanding the documentation above correctly.
