### ISSUE TITLE
Flow flow.yaml changes

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#60]
The tilde was actually intentional, but that doesn't matter right now.  I had used the ~ to indicate that the type referenced in the step wasn't defined in the model.  As long as we can generate Puml, we'll accept this and come up with a more obvious way to handle that later.

_Originally posted by @jondavid-black in https://github.com/jondavid-black/AaC/pull/58#pullrequestreview-786643173_

**Comment by jondavid-black** [comment]
Probably best handled as a discussion.  I think we'll need a way to represent external entities and their interfaces without fully modeling them.  Maybe we can just do that now by building a super simple representation (i.e. model stub?) of the external entity? Perhaps I was trying to solve a problem that doesn't need to be solved?
