### ISSUE TITLE
🐛 [BUG] - Correct Documentation Links

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#657]
### Pre-requisites

- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this issue has not already been filed.

### What version of the AaC package are you using? Check your version with the command: aac version.

0.2.10

### Description

Need to update the url linkages within the documentation to reflect the new org and repo location

### Reproduction URL

n/a

### Reproduction steps

```bash
Please enter an explicit description of your issue
1. Go to documentation
2. See that some links leverage old project and repo
```

### Screenshots

```bash
If applicable, add screenshots to help explain your problem.
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
```

### Pertinent Files

Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

**Comment by jondavid-black** [comment]
I've setup the DNS and custom GitHub Pages URL for arch-as-code.org!

We are officially live with the new site.  If you're updating references we should use the new root URL.
