### ISSUE TITLE
🐛 [BUG] - Component model reference names with spaces are not supported

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#828]
### Pre-requisites

- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this issue has not already been filed.

### What version of the AaC package are you using? Check your version with the command: aac version.

0.4.11

### Description

I'm trying to build a model that references components.  I can create model names that have multiple words with spaces and they pass check.  But if I try to reference that multi-word model name as a component model reference in a parent model it fails to pass check.  If I remove the spaces between the words everything passes checks again.

AaC should let users name their models with multiple words.

### Reproduction URL

https://github.com/DevOps-MBSE/aac-doc-mdl

### Reproduction steps

```bash
It's pretty simple and is described above.  There's an example in the aac-doc-mdl repo (with spaces removed) under ./tests/samples/trade_study/doc/cookie_trade_stydy.aac
```

### Screenshots

```bash
N/A
```

### Logs

```bash
N/A
```

### Pertinent Files

Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

**Comment by lizzcondrey** [comment]
We hit this two sprints or so ago in this iteration as well and have a bug filed to work it. We have it scheduled to be worked during the last sprint of the iteration, which is somewhat set aside for addressing bugs.
