### ISSUE TITLE
📋 [TASK] - Investigate and Design Lexeme Modification

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#915]
### Parent Feature

#914

### Task Description

As an AaC Developer, I want to investigate and design an appropriate updated implementation of the Lexemes, so that I provide a more reliable and useful tool to end users.

### Acceptance Criteria

Spend no more than three days reviewing previously collected reference material and identified impacted areas of AaC core to determine appropriate changes for the current Lexeme Implementation.

**Comment by bunchw** [comment]
The lexeme class does not really have much in it, so the things that need to change are in its implementation and use by Language Error and parsing.
